services:
  postgres:
    image: 'postgres'
    container_name: 'postgres-bignell'
    restart: always
    ports:
      - '15432:5432'
    env_file:
      - .env
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=${DATABASE_USER}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASS}'
